# Generated by Django 5.2.8 on 2025-11-25 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="AllImage")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
